<a href="https://colab.research.google.com/github/hkolgur/UOH/blob/main/numpy_sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Reshape an Numpy array
#### You are given a space separated list of nine integers. Your task is to convert this list into a 3 x 3  NumPy array.

Input Format:

A single line of input containing  space separated integers.

Output Format

Print the 3 x 3  NumPy array.

In [ ]:
arr_np=(np.array([int(x) for x in (input()).split(' ')])) # accept string of int and convert them to numpy array
arr_np.shape=(3,3)
print(arr_np)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### You are given a 2-D array with dimensions N x M 
Your task is to perform the min function over axis  and then find the max of that.

Input Format

The first line of input contains the space separated values of  and .
The next  lines contains  space separated integers.

Output Format

Compute the min along axis 1 and then print the max of that result.

In [ ]:
import numpy as np
arr_shape=([int(x) for x in (input()).split(' ')])
nums=np.array([])
for i in range (0,arr_shape[0]):
  arr_ele=np.array([int(y) for y in (input()).split(' ')])
  if len(arr_ele)!=arr_shape[1]:
    print("Bug")
    break
  else:
    nums=np.append(nums,arr_ele)
    
nums.shape=(arr_shape[0],arr_shape[1])
print(int((nums.min(axis=1)).max()))



2 2
5 6
5 9
5


### You are given two integer arrays of size N x P   and M x P  (M & N are rows, and P is the column). Your task is to concatenate the arrays along axis=0.

Input Format

The first line contains space separated integers N,M and P.
The next N lines contains the space separated elements of the P columns.
After that, the next M lines contains the space separated elements of the  P columns.

Output Format

Print the concatenated array of size (N + M) x P X.



In [ ]:
arr_shape=([int(x) for x in (input()).split(' ')])
arr1=np.array([],dtype=int)
arr2=np.array([],dtype=int)
for i in range (0,arr_shape[0]):
  arr_ele=np.array([int(y) for y in (input()).split(' ')])
  if len(arr_ele)!=arr_shape[2]:
    break
  else:
    arr1=np.append(arr1,arr_ele)

for j in range (0,arr_shape[1]):
  arr_ele=np.array([int(y) for y in (input()).split(' ')])
  if len(arr_ele)!=arr_shape[2]:
     break
  else:
     arr2=np.append(arr2,arr_ele)

arr1.shape=(arr_shape[0],arr_shape[2])
arr2.shape=(arr_shape[1],arr_shape[2])
print(np.concatenate((arr1,arr2),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


### Your task is to print an array of size N x M with its main diagonal elements as 1's and 0's everywhere else.

Input Format

A single line containing the space separated values of N and M.
N denotes the rows.
M denotes the columns.



In [ ]:

np.set_printoptions(legacy='1.13')
arr_shape=([int(x) for x in (input()).split(' ')])
print(np.eye(arr_shape[0],arr_shape[1]))

4 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


## Given two arrays A and B. Both have dimensions of N x N. Compute their matrix product.

Input Format

The first line contains the integer N.
The next  lines contains N space separated integers of array A.
The following N lines contains  space separated integers of array B.

Output Format

Print the matrix multiplication of A and B.

In [ ]:
import numpy as np
arr_shape=int(input())
arr1=np.array([],dtype=int)
arr2=np.array([],dtype=int)
for i in range (0,arr_shape):
  arr_ele=np.array([int(y) for y in (input()).split(' ')])
  if len(arr_ele)!=arr_shape:
    break
  else:
    arr1=np.append(arr1,arr_ele)

for j in range (0,arr_shape):
  arr_ele=np.array([int(y) for y in (input()).split(' ')])
  if len(arr_ele)!=arr_shape:
     break
  else:
     arr2=np.append(arr2,arr_ele)

arr1.shape=(arr_shape,arr_shape)
arr2.shape=(arr_shape,arr_shape)

prod=np.array([],dtype=int)
for i in range(0,arr_shape):
  for j in range(0,arr_shape):
    prod=np.append(prod,np.dot(arr1[i],arr2[:,j]))
    #prod.append(np.dot(arr1[i],arr2[:,j]))
prod.shape=(arr_shape,arr_shape)
print(prod)


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


[[ 7 10]
 [15 22]]


### Samples for reshape with row ,colum major order

In [16]:
import numpy as np
A1=np.random.rand(4,5)
print(A1)
print(np.reshape(A1,20,'F')) #column major order 
print(np.reshape(A1,(10,-1),'C')) #row major Order and -1 tells find the right combination of cols to match 10 rows 
print(np.reshape(A1,(-1,4),'C'))

[[0.09632491 0.23437318 0.20916619 0.42238196 0.30834031]
 [0.97132382 0.54364912 0.91814548 0.20957888 0.77402023]
 [0.44176645 0.65003268 0.48506922 0.65836844 0.87822264]
 [0.65690055 0.03909743 0.18879068 0.15333778 0.18728533]]
[0.09632491 0.97132382 0.44176645 0.65690055 0.23437318 0.54364912
 0.65003268 0.03909743 0.20916619 0.91814548 0.48506922 0.18879068
 0.42238196 0.20957888 0.65836844 0.15333778 0.30834031 0.77402023
 0.87822264 0.18728533]
[[0.09632491 0.23437318]
 [0.20916619 0.42238196]
 [0.30834031 0.97132382]
 [0.54364912 0.91814548]
 [0.20957888 0.77402023]
 [0.44176645 0.65003268]
 [0.48506922 0.65836844]
 [0.87822264 0.65690055]
 [0.03909743 0.18879068]
 [0.15333778 0.18728533]]
[[0.09632491 0.23437318 0.20916619 0.42238196]
 [0.30834031 0.97132382 0.54364912 0.91814548]
 [0.20957888 0.77402023 0.44176645 0.65003268]
 [0.48506922 0.65836844 0.87822264 0.65690055]
 [0.03909743 0.18879068 0.15333778 0.18728533]]


### hstack and vstack samples

In [18]:
ar1=np.random.rand(5,4)
ar2=np.random.rand(5,2)
ar3=np.hstack((ar1,ar2)). #need to pass as a tuple 
print(ar3)

[[0.8431019  0.04615418 0.58128942 0.77128768 0.63757809 0.26144811]
 [0.32831315 0.99434641 0.04626395 0.43379594 0.43603995 0.22106864]
 [0.38271254 0.14322281 0.21515411 0.75425861 0.17632618 0.15462471]
 [0.16388181 0.41381496 0.16183516 0.19029679 0.63986334 0.94162193]
 [0.49366367 0.68952875 0.08632532 0.55785811 0.04786715 0.35546589]]


In [19]:
ar4=np.random.rand(2,3)
ar5=np.random.rand(4,3)
ar6=np.vstack((ar4,ar5)) #need to pass as a tuple 
print(ar6)

[[0.27403359 0.83421101 0.69169139]
 [0.0154781  0.54279037 0.96378672]
 [0.98486244 0.43411363 0.70300367]
 [0.17633782 0.71804131 0.42976871]
 [0.70663936 0.2216331  0.32267373]
 [0.0118082  0.84501857 0.03246997]]


In [ ]:
ar7=np.random.rand(2,3)
ar8=np.random.rand(4,3)
ar9=np.vstack((ar7,ar8)) #need to pass as a tuple 
print(ar6)

In [24]:
arr1=np.random.rand(3,4,2)
arr2=np.random.rand(3,5,2) # (3,5,1) does not work
print(np.hstack((arr1,arr2)))

[[[0.5423802  0.57386918]
  [0.73031658 0.24521932]
  [0.9873554  0.96030483]
  [0.50440769 0.37156437]
  [0.43833252 0.63321151]
  [0.55653523 0.4687567 ]
  [0.71445128 0.01849895]
  [0.57571726 0.90422235]
  [0.54881708 0.27069078]]

 [[0.97857355 0.78671336]
  [0.83145335 0.88962003]
  [0.96098978 0.15216662]
  [0.07676526 0.66278915]
  [0.83663411 0.27063906]
  [0.51188051 0.18550728]
  [0.58692007 0.35522184]
  [0.48259763 0.41715497]
  [0.62228719 0.68071963]]

 [[0.86422966 0.82717076]
  [0.34276304 0.62757747]
  [0.90328366 0.42700989]
  [0.34197479 0.16066288]
  [0.74506805 0.99300456]
  [0.71802621 0.23294001]
  [0.27252901 0.22406397]
  [0.31354497 0.21980347]
  [0.36157888 0.2031893 ]]]


### Using concatenate 

In [26]:
ar1=np.random.rand(5,4)
ar2=np.random.rand(5,2)
ar3=np.concatenate((ar1,ar2),axis=1)  #need to pass as a tuple 
print(ar3)

[[0.86462134 0.35513845 0.63562545 0.47188479 0.0655617  0.53777879]
 [0.87871765 0.45794376 0.10616504 0.20460695 0.04762233 0.22976181]
 [0.98482817 0.41102726 0.1961948  0.03332936 0.41578131 0.856352  ]
 [0.05297695 0.79886349 0.06026274 0.36272293 0.67244133 0.16746051]
 [0.00426684 0.75124554 0.61545122 0.53568488 0.47766359 0.31180879]]


In [27]:
ar1=np.random.rand(2,3)
ar2=np.random.rand(5,3)
ar3=np.concatenate((ar1,ar2),axis=0)  #need to pass as a tuple 
print(ar3)

[[0.88378682 0.03500564 0.26261877]
 [0.87178572 0.32258341 0.36824749]
 [0.19711905 0.68236751 0.52896391]
 [0.21550544 0.54330523 0.63914296]
 [0.8979677  0.88271843 0.99500719]
 [0.18493142 0.94911072 0.10284698]
 [0.47506062 0.1048698  0.21033438]]
